services:
  sqlserver-fideliza:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-fideliza
    hostname: sqlserver-fideliza
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong@Password123"
      MSSQL_PID: "Developer"
    ports:
      - "0.0.0.0:1434:1433"
    volumes:
      - sqlserver_fideliza_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sqlserver_fideliza_data: